"""Stage 3 review report: data/extracted/parse_report.md."""
from __future__ import annotations

import difflib
import re
from collections import Counter

from denombrement import config
from denombrement.parse.structure import Parse, _letters, fold


def alix_contents() -> list[tuple[str, str]]:
    """Alix's table of contents, from "Bailliage de Nancy" to the mines: (heading, page)."""
    path = config.RAW_DIR / "parts" / "02-alix-contents.txt"
    lines = [l for l in path.read_text().splitlines() if not l.startswith("[p.")]
    joined: list[str] = []
    for line in lines:
        if joined and not re.search(r"\d{2,3}\W*$", joined[-1]) and not joined[-1].rstrip().endswith("."):
            joined[-1] = joined[-1].rstrip("-") + ("" if joined[-1].endswith("-") else " ") + line
        else:
            joined.append(line)
    out, on = [], False
    for line in joined:
        if line.startswith("Bailliage de Nancy"):
            on = True
        if fold(line).startswith(("les niynes", "les mynes")):
            break
        if on:
            m = re.match(r"^(.*?)[.\s,]*(\d{2,3})\W*$", line)
            out.append((m.group(1) if m else line.rstrip(" ."), m.group(2) if m else ""))
    return out


def toc_check(result: Parse) -> list[str]:
    """Contents lines without a matching territory heading."""
    headings = {_letters(t.heading)[:40]: t for t in result.territories.values() if t.heading}
    missing = []
    for text, page in alix_contents():
        if re.match(r"^(Les prévoslcz|Aultres villes)", text):
            continue
        key = _letters(text)[:40]
        if not difflib.get_close_matches(key, list(headings), n=1, cutoff=0.6):
            missing.append(f"{text} (p. {page})")
    return missing


def write(result: Parse, chaumes: list[dict]) -> str:
    entries = result.entries
    main = [e for e in entries if e.series == "main"]
    terr = list(result.territories.values())
    lines = ["# Stage 3: parse report", "",
             "Generated by `make parse` from `data/raw/` (Stage 1). Review items for Stage 4.", ""]
    lines += ["## Numbers", "",
              f"- {len(entries)} entries read, numbered 1–{max(e.no for e in entries)}.",
              *[f"- {i}" for i in result.issues],
              f"- {sum(e.cost == 0 for e in entries)} numbers read exactly; "
              f"{sum(0 < e.cost < 1 for e in entries)} through a usual confusion (3/5, 1/4, a letter for a digit); "
              f"{sum(e.cost >= 1 for e in entries)} from a garbled token (listed below).", ""]
    lines += ["| no | read as | cost | entry |", "|---|---|---|---|"]
    for e in entries:
        if e.cost >= 1:
            lines.append(f"| {e.no} | `{e.token}` | {e.cost} | {e.text[:60]} |")
    lines += ["", "## Sections", "",
              f"- Dénombrement entries by section: {dict(Counter(e.section for e in main))}.",
              "- Entries listed before any section heading (`other`, flagged), by district and realm:", ""]
    for (d, r), n in Counter((e.district, e.realm) for e in main if e.section == "other").most_common():
        lines.append(f"  - {n} in `{d}`" + (f" / `{r}`" if r else ""))
    lines += ["", "## Territories", "",
              f"- {len(terr)} territories: {sum(t.hierarchy == 'admin' for t in terr)} divisions, "
              f"{sum(t.hierarchy == 'feudal' for t in terr)} realms, "
              f"{sum(1 for t in terr if t.counterpart and t.hierarchy == 'admin')} counterpart pairs "
              f"({dict(Counter(t.basis for t in terr if t.counterpart and t.hierarchy == 'admin'))}).", "",
              "| page | level | key | parent | ressort | counterpart | printed seat |", "|---|---|---|---|---|---|---|"]
    for t in terr:
        lines.append(f"| {t.page} | {t.level} | `{t.key}` | {t.parent or ''} | {t.ressort or ''} | "
                     f"{t.counterpart or ''} ({t.basis}) | {t.seat_as_printed} |".replace("() ", "").replace(" ()", ""))
    missing = toc_check(result)
    lines += ["", "## Against Alix's table of contents", "",
              f"{len(alix_contents())} contents lines; {len(missing)} without a matching heading:", ""]
    lines += [f"- {m}" for m in missing] or ["- none"]
    lines += ["", "## Holders and shares (for the Claude pass or Stage 4)", ""]
    for t in terr:
        if t.holder_text:
            lines.append(f"- `{t.key}` (p. {t.page}): held by \"{t.holder_text}\"")
    for e in entries:
        if e.share:
            lines.append(f"- {e.no} {e.name} (p. {e.page}): {e.share} — \"{e.share_text[:80]}\"")
    lines += ["", "## Sentences on sovereignty and justice", ""]
    for p in result.prose:
        if re.search(r"souverainet|haulte ?justice|moi[c]?ti[eé]|fi[ec]d", fold(p["text"])):
            lines.append(f"- p. {p['page']} ({p['context']}): {p['text'][:200]}")
    lines += ["", "## Chaumes", "", f"{len(chaumes)} chaumes with their gîtes (`features.jsonl`).", "",
              "## Not parsed by rules", "",
              "- The mines (pp. 116–117): a two-column table with braces that the text layer can't rebuild.",
              "- The rivers (pp. 120–127) and the description of the county of Bitche (pp. 134–171): prose.", ""]
    text = "\n".join(lines) + "\n"
    (config.EXTRACTED_DIR / "parse_report.md").write_text(text)
    return text
